import {GetStaticPaths,GetStaticProps, Metadata} from 'next';


export const metadata: Metadata = {
    title: 'Project | Create Next App',
    description: 'Generated by create next app',
  }
  
export default function Project({ params }: { params: { slug: string } }) {
    return (
        <div className='text-white'>
            Project - {params.slug}
        </div>
    );
}
